BACKLOG-14592 update DisplayActions context
Jahia/content-editor pull request #842
Opened 2020-09-07 14:44 UTC by Taybou

https://jira.jahia.org/browse/BACKLOG-14592

2020-09-07 14:54 UTC, dgriffon requested changes
I am not sure only changing the displayAction to remove the context should be enough.. are you sure component that were using those actions placeholder didn't look for the values of the context and not in the props?

2020-09-07 14:56 UTC, Taybou commented
The component looks to this prop:

```
                icon={context.buttonIcon}
                label={t(context.buttonLabel).toUpperCase()}
                disabled={context.disabled}
                data-sel-role={context.dataSelRole}
                onClick={e => {
                    e.stopPropagation();
                    context.onClick(context, e);
                }}
```

Otherwise, what did you suggest to do?

2020-09-07 15:00 UTC, dgriffon commented
```icon={context.buttonIcon}
                label={t(context.buttonLabel).toUpperCase()}
                disabled={context.disabled}
                data-sel-role={context.dataSelRole}
                onClick={e => {
                    e.stopPropagation();
                    context.onClick(context, e);
                }}```
I mean that we need to change all `context.*` usages to use the prop directly, adding it to the function signature and PropTypes.

2020-09-08 07:04 UTC, dgriffon approved these changes

2020-09-08 07:05 UTC, merged